# Generated by Django 3.2.5 on 2021-10-26 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211026_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeaturevalidators',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productfeaturevalidators',
            name='feature',
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
        migrations.DeleteModel(
            name='ProductFeatureValidators',
        ),
    ]
